### ISSUE TITLE
[patch-ish] linuxmint.com/start dark theme

### ISSUE THREAD

**Issue by iKarith** [linuxmint/linuxmint#303]
Hi, I'm legally blind and light-sensitive, so dark mode is kinda an accessibility thing for me. I downloaded the Mint start page and I decided to see what I needed to do to make it dark mode. Here's what I accomplished:

![minty-start-dark](https://user-images.githubusercontent.com/10780557/94795153-d1cdd180-0391-11eb-8f59-94643da0689a.png)

If you set your GTK+ theme to one the system knows is "dark mode", current firefox will automatically switch to using dark mode if your CSS supports both.

Here's my CSS:

```css
@media (prefers-color-scheme: dark) {
    body {
        color: #eee;
        background: #1b3600 url(../../img/bg-repeat-dark.png) repeat-x 0 0;
    }
    a, a:link, a:visited, a:active{
        color: #999999;
    }
    a:hover{
        color: #666666;
    }

    h1, h1 a {
        color: #b7e680;
    }
    h2 {
        color:#7fb14c;
    }
    h3 {
        color:#67804e;
    }

    #container{
        background: transparent url(../../img/bg-dark.png) no-repeat center top;
    }
    #content{
        background: #1b3600 url(../../img/bg-body-start-dark.png) repeat-x 0 0;
    }

    /* Branding, logo */
    #branding{
        background:url(/img/logo-start-dark.png) no-repeat 0 0;
    }

    #branding a.ir{
        background:url(../../img/logo-start-dark.png) no-repeat 0 0;
    }

    /* You cannot currently change the colors on input[name="q"], Google is
     * rolling out dark mode soon, should be automatic when they do. */

    ul#prefs li.links{
        color:#999;
    }
    ul#prefs li.links a:link{
        background: #f3fea4;
    }
    ul#prefs li.links a:hover{
        background: #84a95c;
        color:#828200;
    }

    #news{
        background: #1d3e02 url(../../img/bg-body-dark.png) repeat-x 0 0;
    }
    #news dt strong{
        color: #6c7d5c;
    }
    #news dd{
        border-bottom: solid 1px #719b54;
    }
    #news dd p.date{
        color: #999;
    }

    #mintLinks{
        background: transparent url(../../img/bg-body-dark.png) repeat-x 0 -100px;
    }

    #userGuideList{
        background: #000;
        border: solid .4em #6c7c5c;
    }
}
```

This can be appended to your existing CSS. You'll need to edit the paths to your img dir since I just put them in a subdir in my home directory. 🤷‍♂ I'll attach the png files I created shortly.
