### ISSUE TITLE
 Random wifi disconnect and bluetooth disabled (random airplane mode)

### ISSUE THREAD

**Issue by VoldemortsCupcakeBakery** [linuxmint/linuxmint#625]
Several times during the day, the wifi disconnects and also Bluetooth is disabled without me prompting the PC to do so. Hitting the airplane button (F11) after that ends the airplane mode and operation goes back to normal. The wifi adapter seems to be newish as I had to install the Edge version of Mint to get it working. I did not fiddle with drivers or their configs, with Edge the wifi just worked out of the box.

I attached what dmesg gives me when the disconnect happens. Mind that the button mentioned was not pressed by me. Mint also seems to have trouble with the driver for the wifi adapter (rtw89_8852ce) as suggested by the error in the log.
[log.txt](https://github.com/linuxmint/linuxmint/files/13425851/rtwlog2.txt)

**My specs:**
Distribution: Linux Mint 21.2 x86_64 (Linux Mint Edge) with Cinnamon 5.8.4
Kernel version: 6.2.0-36-generic #37~22.04.1-Ubuntu
PC: HP Pro x360 435 13.3 inch G10 Notebook
CPU/GPU: AMD Ryzen 5 7530U with Radeon Graphics (AMD Barcelo)

inxi -Fxxxrz gives me:
```
Network:
  Device-1: Realtek vendor: Hewlett-Packard driver: rtw89_8852ce v: kernel
    pcie: speed: 5 GT/s lanes: 1 port: 2000 bus-ID: 01:00.0 chip-ID: 10ec:c852
    class-ID: 0280
  IF: wlp1s0 state: up mac: <filter>
```
